### PR TITLE
Responsive Navigation Bar

### PR DESCRIPTION
**Pull request by amitmaindola**
## No other parts of the website were affected while making this.
image
image

### CODE REVIEW

**Comment by amitmaindola** [comment]
### PS: If you feel any type of bug at any point in the future you can just comment that here, I will resolve that.   😄

**Comment by amitmaindola** [comment]
@sunilkrbajpai  please accept my PR as I am participating in hacktoberfest 2021

**Comment by sunilkrbajpai** [comment]
Good work

**Comment by amitmaindola** [comment]
Kindly accept the pull request and merge this PR, So that this will be counted for Hacktoberfest 2021.

**Comment by amitmaindola** [comment]
Thank you for marking as hacktoberfest-accepted. 😄 .
Now should I close this PR, or leave it open.

**Pull request closed without merging**
